import pandas as pd
import matplotlib.pyplot as plt
iris_data = pd.read_csv('iris.csv')
print("a. First 5 records:")
print(iris_data.head())
print("b. Data cleaning concepts:")
print("Missing values:")
print(iris_data.isnull().sum())
print("c. Last 10 records:")
print(iris_data.tail(10))
print("d. Data analysis operations:")
print("Descriptive statistics:")
print(iris_data.describe())
print("e. Analysis in graphical format:")
plt.figure(figsize=(8, 6))
plt.scatter(iris_data['sepal.length'], iris_data['sepal.width'], color='blue', label='Sepal')
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.title('Sepal Length vs Sepal Width')
plt.legend()
plt.show()